import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const requests = sqliteTable("requests", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  type: text("type").notNull(),
  name: text("name").notNull(),
  institution: text("institution").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  role: text("role"),
  location: text("location"),
  need: text("need"),
  urgency: text("urgency"),
  equipment: text("equipment"),
  description: text("description").notNull(),
  product: text("product"),
  brand: text("brand"),
  model: text("model"),
  category: text("category"),
  serial: text("serial"),
  errorCode: text("error_code"),
  criticality: text("criticality"),
  startedAt: text("started_at"),
  quantity: integer("quantity"),
  operation: text("operation"),
  condition: text("condition"),
  estimatedDate: text("estimated_date"),
  clinicalNeed: text("clinical_need"),
  accessories: text("accessories"),
  installationRequired: integer("installation_required", { mode: "boolean" }).notNull().default(false),
  trainingRequired: integer("training_required", { mode: "boolean" }).notNull().default(false),
  maintenanceRequired: integer("maintenance_required", { mode: "boolean" }).notNull().default(false),
  context: text("context"),
  sourceUrl: text("source_url"),
  attachmentKey: text("attachment_key"),
  status: text("status").notNull().default("nuevo"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});

export const contentItems = sqliteTable("content_items", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  kind: text("kind").notNull(),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  summary: text("summary").notNull().default(""),
  status: text("status").notNull().default("borrador"),
  featured: integer("featured", { mode: "boolean" }).notNull().default(false),
  payload: text("payload").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()),
});
